# Generated by Django 3.1.4 on 2020-12-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='mobile',
            field=models.TextField(blank=True, max_length=10),
        ),
    ]
