# Generated by Django 3.1.4 on 2020-12-17 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_auto_20201216_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=15)),
                ('ingredients', models.CharField(max_length=15)),
                ('description', models.TextField()),
                ('suitable_for', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=30)),
                ('weight', models.IntegerField()),
                ('weight_tag', models.CharField(choices=[('kilograms', 'Kilograms'), ('grams', 'Grams'), ('pounds', 'Pounds'), ('ounces', 'Ounces')], default='grams', max_length=12)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('image', models.ImageField(upload_to='food')),
                ('image_one', models.ImageField(upload_to='food')),
                ('image_two', models.ImageField(upload_to='food')),
                ('image_three', models.ImageField(upload_to='food')),
            ],
        ),
        migrations.CreateModel(
            name='CommentsOfFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.food')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
            ],
        ),
    ]
