# Generated by Django 3.1.4 on 2020-12-16 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='image_five',
            field=models.ImageField(blank=True, upload_to='pets'),
        ),
    ]
