# Generated by Django 3.1.4 on 2020-12-16 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_pet_image_five'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='image_five',
            field=models.ImageField(upload_to='pets'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='image_four',
            field=models.ImageField(upload_to='pets'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='image_three',
            field=models.ImageField(upload_to='pets'),
        ),
    ]
