# Generated by Django 3.1.4 on 2020-12-17 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_auto_20201216_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='animal',
            field=models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('parrot', 'Parrot'), ('mouse', 'Mouse'), ('spider', 'Spider'), ('snake', 'Snake'), ('lizard', 'Lizard'), ('chameleon', 'Chameleon'), ('fish', 'Fish'), ('monkey', 'Monkey')], default='dog', max_length=20),
        ),
    ]
