# Generated by Django 3.1.1 on 2020-11-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='image_url',
            field=models.ImageField(upload_to='pets'),
        ),
    ]
