# Generated by Django 3.1.4 on 2020-12-03 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0006_auto_20201203_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='like',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='user',
        ),
    ]
