# Generated by Django 3.1.4 on 2020-12-05 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0012_auto_20201203_2003'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='price',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=7),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pet',
            name='type',
            field=models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('parrot', 'Parrot'), ('mouse', 'MOUSE'), ('spider', 'SPIDER'), ('unknown', 'Unknown')], default='unknown', max_length=7),
        ),
    ]
