# Generated by Django 3.1.4 on 2020-12-05 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0014_auto_20201205_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='type',
            field=models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('parrot', 'Parrot'), ('mouse', 'Mouse'), ('spider', 'Spider'), ('unknown', 'Unknown')], default='unknown', max_length=17),
        ),
    ]
