# Generated by Django 3.1.4 on 2020-12-17 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_auto_20201216_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toy_name', models.CharField(max_length=15)),
                ('material', models.CharField(max_length=15)),
                ('description', models.TextField()),
                ('suitable_for', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=30)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('image', models.ImageField(upload_to='toys')),
                ('image_one', models.ImageField(upload_to='toys')),
                ('image_two', models.ImageField(upload_to='toys')),
                ('image_three', models.ImageField(upload_to='toys')),
            ],
        ),
        migrations.CreateModel(
            name='Liked',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked', models.CharField(max_length=5)),
                ('toy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toys.toys')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CommentsOfToys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('toy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='toys.toys')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
            ],
        ),
    ]
