# Generated by Django 3.1.4 on 2020-12-17 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=15)),
                ('ingredients', models.CharField(max_length=15)),
                ('description', models.TextField()),
                ('suitable_for', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=30)),
                ('weight', models.IntegerField()),
                ('weight_tag', models.CharField(choices=[('grams', 'Grams'), ('pounds', 'Pounds'), ('ounces', 'Ounces')], default='grams', max_length=12)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('price_tag', models.CharField(choices=[('lev', 'Lev'), ('dollar', '$'), ('euro', 'Euro')], default='dollar', max_length=12)),
                ('image', models.ImageField(upload_to='medicine')),
                ('image_one', models.ImageField(upload_to='medicine')),
                ('image_two', models.ImageField(upload_to='medicine')),
                ('image_three', models.ImageField(upload_to='medicine')),
            ],
        ),
    ]
