# Generated by Django 3.1.4 on 2020-12-19 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0004_auto_20201216_1359'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('servicing', models.DecimalField(decimal_places=1, max_digits=2)),
                ('mailing', models.DecimalField(decimal_places=1, max_digits=2)),
                ('publishing', models.DecimalField(decimal_places=1, max_digits=2)),
                ('orders', models.DecimalField(decimal_places=1, max_digits=2)),
                ('content', models.TextField(blank=True)),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userprofile')),
            ],
        ),
    ]
